# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog

"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}\
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | split(pat="\n") | first }}
    {% endfor %}\
{% endfor %}\n
"""
trim = true
postprocessors = [
  { pattern = '#(\d+)', replace = "[#$1](https://github.com/uptick-ads/shopify-extensibility/issues/$1)" },
]

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_preprocessors = []
commit_parsers = [
  { message = "^work:", skip = true },
  { message = "^feat", group = "<!-- 0 -->🚀 Added" },
  { message = "^fix", group = "<!-- 1 -->🐛 Fixed" },
  { message = "^doc", group = "<!-- 3 -->📚 Documentation" },
  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
  { message = "^style", group = "<!-- 5 -->🎨 Styling" },
  { message = "^test", group = "<!-- 6 -->🧪 Testing" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps.*\\)", skip = false },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^(test|chore|ci): Fixing.*(lint|test)s?", skip = true },
  { message = "^(test|chore|ci): Updating CHANGES.*", skip = true },
  { message = "^Merge branch.*into.*", skip = true },
  { message = "^Merge pull request.*from.*", skip = true },
  { message = "^Generating CHANGES", skip = true },
  { message = "^chore|^ci", group = "<!-- 7 -->🔧 Miscellaneous" },
  { body = ".*security", group = "<!-- 8 -->🛡️ Security" },
  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },
  { message = "^build", group = "<!-- 10 -->🔨 Build" },
  { message = ".*", group = "<!-- 11 -->✨ Changed" }
]
protect_breaking_commits = false
filter_commits = false
topo_order = false
sort_commits = "oldest"
