name: "Test"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

run-name: "${{ github.event.head_commit.message || github.workflow }}"

jobs:
  GenerateChangelog:
    runs-on: ubuntu-latest
    name: Generate Changelog
    if: >
      github.event_name == 'pull_request' &&
      github.actor != 'dependabot[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.ref != 'refs/heads/main'

    steps:
      - name: Load credentials
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PPX_DIGITAL_ACTIONS_PAT: op://uptick-production/github-actions/github-personal-access-token

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ env.PPX_DIGITAL_ACTIONS_PAT }}

      - name: Check for CHANGES.md
        id: check_changes
        uses: andstor/file-existence-action@v3
        with:
          files: CHANGES.md

      - name: Generate a changelog
        if: steps.check_changes.outputs.files_exists == 'false'
        uses: orhun/git-cliff-action@v4.7.1
        with:
          config: cliff.toml
          args: --unreleased
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and push CHANGES.md
        if: github.ref != 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: CHANGES.md
          message: "Generating CHANGES.md"

      - name: Make sure we can read the CHANGELOG
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: none
          version: "Unreleased"
          path: ./CHANGES.md

  Lint:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.actor != 'uptick-bot' ||
          github.event_name == 'pull_request' ||
          (github.actor == 'uptick-bot' && github.event.head_commit.message == 'Generating CHANGES.md') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run Lint check
        run: npm run lint

  Test:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.actor != 'uptick-bot' ||
          github.event_name == 'pull_request' ||
          (github.actor == 'uptick-bot' && github.event.head_commit.message == 'Generating CHANGES.md') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test

